run("Previous Slice [<]");
run("Delete Slice");
run("Previous Slice [<]");
run("Delete Slice");
run("Previous Slice [<]");
run("Delete Slice");
run("Previous Slice [<]");
run("Delete Slice");
run("Previous Slice [<]");
run("Delete Slice");
run("Previous Slice [<]");
run("Delete Slice");
run("Previous Slice [<]");
run("Delete Slice");
run("Previous Slice [<]");
run("Delete Slice");
run("Previous Slice [<]");
run("Delete Slice");
run("Previous Slice [<]");
run("Delete Slice");
run("Previous Slice [<]");
run("Delete Slice");
run("Previous Slice [<]");
run("Delete Slice");
run("Previous Slice [<]");
run("Previous Slice [<]");
run("Delete Slice");
run("Previous Slice [<]");
run("Delete Slice");
run("Previous Slice [<]");
run("Delete Slice");
run("Previous Slice [<]");
run("Delete Slice");
run("Previous Slice [<]");
run("Delete Slice");
run("Previous Slice [<]");
run("Delete Slice");
run("Previous Slice [<]");
run("Delete Slice");
run("Previous Slice [<]");
run("Delete Slice");
run("Previous Slice [<]");
run("Delete Slice");
run("Previous Slice [<]");
run("Delete Slice");
run("Previous Slice [<]");
run("Delete Slice");
run("Previous Slice [<]");
run("Delete Slice");
run("Previous Slice [<]");
run("Previous Slice [<]");
run("Delete Slice");
run("Previous Slice [<]");
run("Delete Slice");
run("Previous Slice [<]");
run("Delete Slice");
run("Previous Slice [<]");
run("Delete Slice");
run("Previous Slice [<]");
run("Delete Slice");
run("Previous Slice [<]");
run("Delete Slice");
run("Previous Slice [<]");
run("Delete Slice");
run("Previous Slice [<]");
run("Delete Slice");
run("Previous Slice [<]");
run("Delete Slice");
run("Previous Slice [<]");
run("Delete Slice");
run("Previous Slice [<]");
run("Delete Slice");
run("Previous Slice [<]");
run("Delete Slice");
run("Previous Slice [<]");
run("Previous Slice [<]");
run("Delete Slice");
run("Previous Slice [<]");
run("Delete Slice");
run("Previous Slice [<]");
run("Delete Slice");
run("Previous Slice [<]");
run("Delete Slice");
run("Previous Slice [<]");
run("Delete Slice");
run("Previous Slice [<]");
run("Delete Slice");
run("Previous Slice [<]");
run("Delete Slice");
run("Previous Slice [<]");
run("Delete Slice");
run("Previous Slice [<]");
run("Delete Slice");
run("Previous Slice [<]");
run("Delete Slice");
run("Previous Slice [<]");
run("Previous Slice [<]");
run("Delete Slice");
run("Previous Slice [<]");
run("Delete Slice");
