function [fitresult, gof] = createFit(peak_x, peak_y)
%CREATEFIT(PEAK_X,PEAK_Y)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : peak_x
%      Y Output: peak_y
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 16-Dec-2019 16:08:01


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( peak_x, peak_y );

% Set up fittype and options.
ft = fittype( 'exp2' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [585349.807561151 -0.0315238297523274 1.08100376212687 -1.60697558301422e-05];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );




